### ISSUE TITLE
Phoneme representation

### ISSUE THREAD

**Issue by tebin** [nobody996/FastSVC#2]
Which phonetic representation do you use? Most English TTS implementations seem to use Arpabet, but since FastSVC supports cross-lingual conversion like the Chinese-English one shown in the demo, I assume that's not the case here. My gut tells me it's IPA which is generated by libraries like [Phonemizer](https://github.com/bootphon/phonemizer) - in fact this is the method that [DeepSinger](https://arxiv.org/abs/2007.04590) uses, which is another SVS paper that supports both English and Chinese - but your clarification would be appreciated.

**Comment by ghost** [comment]
@tebin are you working on a implementation of this, would be interested to help

**Comment by nobody996** [comment]
Sorry for the late reply. We used English phonset ARPAbet.
